name: License Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  license-check:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     - uses: fossas/fossa-action@main # Use a specific version if locking is preferred
       with:
         api-key: ${{secrets.FOSSA_API_KEY}}
         
